GET http://localhost:3000/foods

####

GET http://localhost:3000/foods/1

###

POST http://localhost:3000/foods
Content-Type: application/json

{
  "name": "burger",
  "price": 5
}
###

PATCH http://localhost:3000/foods/4
Content-Type: application/json

{
  "name": "the burger"
}